language: go

go:
  - 1.5
  - 1.4
  - 1.3
  - tip

addons:
  postgresql: "9.3"

services:
  - postgresql

script:
  - ./script/test

before_install:
  - sudo apt-get update
  - sudo apt-get install -y tor

install:
  - ./script/bootstrap
  - ./script/recycle
